### ISSUE TITLE
Token Lending Program Is Not Deployed On Devnet

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana-program-library#1737]
The readme for the token lending program suggests that it is deployed on devnet, however visiting the explorer for programid that is given shows that the account does not exist https://explorer.solana.com/address/LendZqTs8gn5CTSJU1jWKhKuVpjJGom45nnwPb2AMTi?cluster=devnet

**Comment by joncinque** [comment]
@jordansexton should be able to help you out -- I believe he's been working on getting the program up everywhere

**Comment by jordansexton** [comment]
We've been waiting to redeploy to get [Pyth supported](https://github.com/solana-labs/solana-program-library/pull/1757) (ready for review) and a [CLI working](https://github.com/solana-labs/solana-program-library/pull/1676) (WIP). As of right now, flux-aggregator can't be used out of the box for prices, and there's no easy way to create markets and reserves to get started. @bonedaddy hope those two PRs help.

**Comment by kuznetsov-m** [comment]
Token Lending Program in Devnet
https://explorer.solana.com/address/LendZqTs7gn5CTSJU1jWKhKuVpjJGom45nnwPb2AMTi?cluster=devnet

**Comment by jordansexton** [comment]
The lending program has been redeployed to devnet with Serum v3 support @ https://explorer.solana.com/address/Fo1J5WWXeuD6t8sDXLDDRjrjA8FwB9VizV19CfutRU48?cluster=devnet

This is in order to get https://solana-labs.github.io/oyster-lending/ running again, which only supports single collateral borrows. Feel free to reopen if this doesn't resolve your issue.

Separately, I'm working on getting the UI working for cross collateral. Once that's done, the lending progam @ `LendZqTs7gn5CTSJU1jWKhKuVpjJGom45nnwPb2AMTi` will likely be redeployed across dev/test/mainnet.

**Comment by jordansexton** [comment]
(Also as @kuznetsov-m notes, there was a typo in the original address link.)
