### ISSUE TITLE
Token.getAssociatedTokenAddress does not need to be `async`

### ISSUE THREAD

**Issue by mgild** [solana-labs/solana-program-library#2661]

**Comment by jordansexton** [comment]
See #2539 / #2641 for the latest developments in the SPL Token bindings.

This function is still async though: https://github.com/solana-labs/solana-program-library/blob/a966bde23b3ec9871ff15520fec7773d2673a224/token/ts/src/state/mint.ts#L114

This is because it relies on https://solana-labs.github.io/solana-web3.js/classes/PublicKey.html#findProgramAddress which is async.
