### ISSUE TITLE
BPF Loader 2 program stuck

### ISSUE THREAD

**Issue by NLObedear** [solana-labs/solana-program-library#2708]
I have attempted to upload program 3QcKZhx87sJvWfVs43ibfJvNzgnwv4BEAqfqUgadBDQw, although it has gotten stuck between being a Buffer and a program. I have ensured that this address (DC6tuNT7QmAu3vdNyRUw2LJ1NYncTEr6DTEKfhc8PxJv ) is currently being used in the CLI and I am on the same network as when I attempted to deploy

I have checked any open buffers under wallet DC6tuNT7QmAu3vdNyRUw2LJ1NYncTEr6DTEKfhc8PxJv and none exist, This wont allow me to close it or attempt to redeploy it. 

Whenever I attempt to redeploy it via keypair or address I am given this error: 
Error: 3QcKZhx87sJvWfVs43ibfJvNzgnwv4BEAqfqUgadBDQw is not a Program or Buffer account

Here is the link to the BPF program. 
https://solscan.io/account/3QcKZhx87sJvWfVs43ibfJvNzgnwv4BEAqfqUgadBDQw

Not sure what to do as I cant redeploy or close this program and feel its a bug. I was also having issues with program deployment not working at all before this. and this program has an unusual amount of write transactions

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, so please join us on Discord in #developer-support https://discord.gg/JJkWhPjb

To quickly answer your question, this could be because the program is using `BPFLoader2` instead of `BPFLoaderUpgradeable`.  You'll need to resume your deployment using the keypair for `3QcKZhx87sJvWfVs43ibfJvNzgnwv4BEAqfqUgadBDQw` and `solana deploy`, the old version of the command that talks to BPFLoader2, instead of using `solana program deploy`, which uses `BPFLoaderUpgradeable`.
