### ISSUE TITLE
token: please document that spl token program is deployed under some kind of dao/multisignature

### ISSUE THREAD

**Issue by dzmitry-lahoda** [solana-labs/solana-program-library#2713]
like these 

https://github.com/saber-hq/captain
https://github.com/DeployDAO/migrator

just to make sure basics trusted by people are safe.  same asked for vesting (https://github.com/Bonfida/token-vesting/issues/27 similar)

**Comment by joncinque** [comment]
Since it's so fundamental to the operation of the chain, the SPL token program is handled as a runtime feature, with deployments controlled using the `solana feature` tool: https://docs.solana.com/cli/usage#solana-feature

With the next release, we will publish how to verify the build using the Anchor verifiable build tool: https://project-serum.github.io/anchor/getting-started/verification.html

**Comment by joncinque** [comment]
Now that token 3.3.0 is released, let me know if the release notes make it clear how it's released: https://github.com/solana-labs/solana-program-library/releases/tag/token-v3.3.0
