### ISSUE TITLE
DelegatedFreezeAccount Instruction: Prevent user from removing delegate

### ISSUE THREAD

**Issue by jpbogle** [solana-labs/solana-program-library#2823]
We have been thinking long and hard about utilizing freeze_authority + delegate to enable temporary and conditional ownership of tokens. (https://cardinal.so) So the user claims the token and it in same instruction delegates it and gets their token-account frozen so it can be revoked on demand.

We have been building a protocol for doing this for new tokens and were planning to try to enable this functionality for existing NFTs (whose freeze_authority is held by metaplex-token-metadata)

Our proposal there was going to be this: freeze/unfreeze instructions that proxy instruction through to spl_token_program IF the signer is the delegate of the single token in the token_account that they are trying to freeze. 
(WIP https://github.com/cardinal-labs/metaplex-program-library/commit/efa533c544628864a8f409c00cfb6c1fbdbf6dbb)

In other words, if someone delegated you the NFT in a token account, you can freeze that token account. This works for NFTs afaict and we were just realizing that it maybe could apply to all token_accounts (if ALL tokens in the account are delegated to you).

Essentially this opens up a world of possibilities around conditional ownership, rentals, time-revoking tokens etc. where you as the holder can claim it but agree by signing away delegate rights that this other program can manage / revoke it from you.

Is this something that makes sense to just add into spl-token program? I can't think of any reasons this would cause issues. The only interesting thing is that if I delegate tokens to someone, they could always freeze my account forever, but they also could always just take the tokens so I think thats okay.

One thing I just thought of was that if this is your ATA, outright freeze might cause you to not be able to accept new tokens. This is a non-issue with NFTs of course but may be a concern with regular tokens potentially. Maybe it should enforce non-ATA if it were to work with FTs.

@joncinque

**Comment by joncinque** [comment]
We're working on adding functionality to the token program through extensions, and in this case, it seems like you want an extension to token accounts for an account-specific freeze authority, in addition to the mint-wide freeze authority.

So for example, I instantiate the account that holds the NFT, and then add some other program-derived address as the freeze authority.

Is that correct?

**Comment by jpbogle** [comment]
ya essentially. Though we would also like to enable this for all existing tokens as well so that we can create rentals this way.

**Comment by jpbogle** [comment]
i think really what we want is an account specific clawback / a delegate that cannot be removed by the holder, freeze is just the way we would achieve that currently

**Comment by jpbogle** [comment]
hey @joncinque, was just thinking about this suggestion again and didnt realize we had that much time to get features into token-program-22. Was thinking about making a PR around a `freeze/thaw_delegated_token_account` instruction which checks if

1. you (signer) is the delegate
2. All tokens in the token_account are delegated to that user
3. This token_account is not the ATA

and if so it freezes/thaws the token account. We have modeled this the same in that metaplex PR above and have been using it to do rentals of NFTs. Since its backwards compatible with state in theory it should be safe and not need to be modeled as an "extension".

trying to catch up with the `withdraw_withheld_tokens` instruction, since i thought it sounds like this actually achieves something similar if im understanding correctly 
https://github.com/solana-labs/solana-program-library/pull/2857

but the withhold authority still also requires that the account is frozen to actuall withdraw and the only way to freeze still is via freeze_authority?
https://github.com/solana-labs/solana-program-library/pull/2857/files#diff-670d6d1069e6f568427f36c934cde28bf82c9e71acc9f4b78a4e13104599e85eR234-R236

If we contributed this feature, it is basically a way to achieved a "non-revocable" delegate. Perhaps the "WithdrawAuthority" should just be used for this, but maybe instead of HAVING to freeze the token_account, transfer of those tokens is blocked if there is a withdraw authority on them. I think the freeze_delegated_account approach makes sense because its basically just saying that if you are the delegate instead of taking the tokens, you can reserve your right to take them in their token account.

**Comment by joncinque** [comment]
Adding this as an extension makes the most sense to me, rather than relying on some hacky behavior reusing the delegate in an unexpected way.  It'll confuse people in the long run.  It would be a simple extension that just adds an external freeze authority, configurable by the owner at any time as long as the account is not frozen.  You would give that freeze authority to the program and call them to freeze your account.

So you would delegate the tokens *as well* beforehand, and that way anytime the authority wants to use the tokens, they can thaw, transfer out, and freeze again within the the same transaction, correct?

The withheld tokens that you're referencing are related to transfer fees.  When transferring a token with a fee, some amount of the tokens is withheld for the fee owner.  I don't think they'll help you for this situation.

**Comment by akutruff** [comment]
I added an earlier issue for this.  

https://github.com/solana-labs/solana-program-library/issues/2762

I too am doing the freeze/unfreeze way of enforcing token control.  It sucks for users because they see an NFT in their wallet and wish to transfer it to another wallet and they get an error because its frozen.  Under some conditions, I want to let them transfer without restriction, but I need to be able to take complete control of the token from whoever is holding the token after the transfer.

So I don't want to freeze their account entirely or force them to do transfers through my UI rather than directly in their wallet.  Wallets would need to understand what my program allows

The key subtlety in what I'm looking for is that a program should be able to control what operations are allowed by the user and the user may not revoke a delegate and transfers do not remove the delegate.  

I think what will address every possible scenario:

1. Programs can set a token mint to have a permanent delegate.
2. The delegate has permission flags for itself so the user knows the scope of the tokens control: `can_burn` `can_transfer` `can_revoke_delegate` `can_revoke_other_permanent_delegate` etc.
3. A permanent delegate can do any operation it's flags allow at any time.
4. A permanent delegate cannot be revoked by the user.
5. Transfers do not change a permanent delegate.
6. A permanent delegate can revoke itself as a permanent delegate.

The above design not only addresses the problems in this thread, but also is the implementation for freezing.

**Comment by akutruff** [comment]
@joncinque Is it too late to consider this?

**Comment by akutruff** [comment]
@joncinque bump, please.  Apologies for the nag, but I can't find any roadmap or general approach to handling permissions in Token 2022, and I am concerned about it all being done piecemeal.

**Comment by joncinque** [comment]
I'm bearish about such a heavy hand, since a permanent delegate essentially owns all tokens on the mint, and would prefer something a bit more specific to the use-case, implemented as an extension.

This is even if you want to use tokens! NFTs are not particularly well suited to the spl-token programs, since there's so much extra stuff that's unnecessary.

All that to say, I don't intend on implementing this functionality, but I'll be happy to discuss a well-scoped PR that addresses the issue through an extension on token-2022.

For reference, you can follow everything that we're doing for token-2022 at this GitHub project: https://github.com/orgs/solana-labs/projects/4

**Comment by akutruff** [comment]
@joncinque 
> This is even if you want to use tokens! NFTs are not particularly well suited to the spl-token programs, since there's so much extra stuff that's unnecessary.

Thanks for the reply!

Would you mind expanding on this comment?  The use of the spl-token programs is pretty much required to operate within the web3 ecosystem.  What are you saying is unnecessary?

**Comment by joncinque** [comment]
It depends on what you want to do in the web3 ecosystem.  spl-token is designed for fungible tokens, so it separates a mint with a supply, mint / freeze authorities, etc, and then a token account with its associated mint, owner, amount, close authority etc etc etc.  

For an NFT, the bare minimum requirement is a proof of ownership, so the entire account data could literally just be the owner's pubkey, no mint required!  With that model, you'd save a lot on rent, and still get what you need, ie. create (mint), transfer, burn, close.  Then you can add extensions for freezing, delegates, and all that.

**Comment by akutruff** [comment]
Thanks again.   

Wallets have integrated with spl-token program tokens and metaplex metadata.  For a service to deviate from that, and roll our own tokens is to pass up that rich UX, and for users to auction their tokens on OpenSea etc.  The fact that NFT's are standardized is why it all works.  I'm kind of speechless that you're saying NFT's are not ideally used with the spl-token program.

**Comment by anthonylekan** [comment]
Completely agree with you, Andy. We're looking for this functionality as well.
