### ISSUE TITLE
SPL Stake Pool and CLI - v0.6.4 - Not yet published to Crates.io

### ISSUE THREAD

**Issue by ndollar** [solana-labs/solana-program-library#2931]
cc @joncinque 

I just started getting an error creating a stake pool locally and I saw that there was a recent version bump of `spl-stake-pool-cli` but it hasn't yet made it to Crates.io

![image](https://user-images.githubusercontent.com/1976630/154611165-d657e671-771f-4358-a614-f9d7085e1fa1.png)

From the README it looks like publish is a manual step ... @joncinque are you planning to publish the latest version? Thanks!

**Comment by joncinque** [comment]
There's an issue with publishing the CLI 0.6.4 because of a dependency on associated-token-account v1.0.5, which also hasn't been published unfortunately.  To make things clearer, I'll yank the spl-stake-pool 0.6.4 crate until associated-token-account is released, which should be some time next week, assuming that the cluster upgrades not too slowly :crossed_fingers:

**Comment by CMEONE** [comment]
I also started getting an error on localnet when doing final tests before mainnet-beta deployment (as @joncinque knows, I was able to successfully deploy to devnet a few months back).

```
RPC response error -32002: Transaction simulation failed: Error processing Instruction 2: insufficient account keys for instruction [9 log messages]
```

I assume the `insufficient account keys for instruction` error is related to this issue. I was able to deploy just fine back in December, I think that was still the `v0.6.3` crate. I just tried deploying to testnet (without any updates to any of the CLI tools since I first installed back in December), and when that returned the above error, I tried updating `solana` to `v1.9.8` and running a local validator, got the same response, tried downgrading `solana` to mainnet `v1.8.16` and now getting `error sending request for url (http://127.0.0.1:8899/): connection closed before message completed`.

Are there any workarounds for the time being? I was hoping to target a launch on mainnet-beta by end of Monday or Tuesday, but I'm using pre-generated keys that have already been registered in token registries and don't want to brick that if mainnet-beta deployment fails. Are there any things I need to be aware of to avoid these issues and guarantee that deployment will absolutely work on the first try on mainnet-beta?

**Comment by ndollar** [comment]
@CMEONE that's the same error I got .. @joncinque is this change a backward-incompatible change in the number of accounts for the instruction?

**Comment by CMEONE** [comment]
According to semver, anything can be a breaking change in the stake pool as it hasn't hit version 1, but according to #2791 there was a potentially breaking change in the token program (which I believe is related to this issue) implemented from v1.0.3 to v1.0.4 (which goes against semver).

@joncinque is there any workaround for the time being? The reason I was running the pool against a test validator even after confirming over the course of months that it works on devnet is because I've got one shot at the deployment on mainnet-beta (if I mess that up, it sets back our launch by months as we would have to go through the slow process of working with wallet providers to update the token addresses in their registries), I am even willing to "waste" a few SOLs on test deployments (with randomly generated keys) on mainnet-beta before deploying with the real pre-generated keys to mainnet-beta, but I want to be certain that it won't be in vain and that the pool program deployment flow still works properly on mainnet-beta (even if it doesn't on testnet or localnet).

**Comment by joncinque** [comment]
Sorry for the late responses here.  To answer all the questions...

The breakage while creating a pool is due to the added account required during `initialize`: https://github.com/solana-labs/solana-program-library/pull/2636/files#diff-af2a227387cf96f6a98cd329cccbec0801d61f65024483db37cec15c58a24a56R412

> Are there any workarounds for the time being?

Please build from source!

**Comment by CMEONE** [comment]
Ok, I will try this out within a few days and let you know. Thanks again for all of your help and guidance!

**Comment by neighbaa** [comment]
@CMEONE thank you so much for raising this! We've encountered exactly the same error while following the Solana quickstart docs.

> Please build from source!

Roger that. @joncinque thank you!

**Comment by shravanshetty1** [comment]
Similar issue with https://crates.io/crates/spl-associated-token-account/versions

**Comment by joncinque** [comment]
@POPE001 Essentially, you need to run `cargo build` from `stake-pool/cli`.  You can read more information about building at our docs https://github.com/solana-labs/solana-program-library#build

This isn't for technical support however, so please go to #developer-support in Discord https://solana.com/discord

**Comment by CMEONE** [comment]
I just wanted to confirm that building from source did indeed work for the deployment. We're finally deployed on mainnet-beta at [stake.solblaze.org](https://stake.solblaze.org/). Thank you for all of your guidance and support @joncinque, we were so glad to be able to help out and test the stake pool JS bindings!

**Comment by joncinque** [comment]
Apologies for the long wait, but this is finally done.  Because of the dependencies on later token / associated token account crates, the CLI is on a different tag: https://github.com/solana-labs/solana-program-library/releases/tag/stake-pool-cli-v0.6.4
