### ISSUE TITLE
Can't import the named export 'bool' from non EcmaScript module (only default export is available) - spl-token@0.2.0

### ISSUE THREAD

**Issue by Beardev118** [solana-labs/solana-program-library#3014]
I can't use the spl-token 0.2.0 version 
I have got this error 
![image](https://user-images.githubusercontent.com/55624311/159099636-61fd82c5-5ec7-45a2-b95e-c2a72bdfa4c8.png)

**Comment by jordansexton** [comment]
Hmm this looks like it may be an issue with your build tool/config/environment. It's caused by something not handling ES module imports correctly.

In general for error reports like this to be useful, there needs to be more complete context about your projects. Please provide a link to a repo that reproduces the issue, since that will help determine the cause.

**Comment by dtand** [comment]
I think this issue is already resolved here:

https://github.com/solana-labs/wallet-adapter/issues/265

Looks to be related to react create apps v4.  The solution mentioned by [steveluscher](https://github.com/steveluscher) worked for me.

**Comment by jordansexton** [comment]
Ah, yeah. CRA 4 is generally not good at handling native ESM. There's a [CRA5-based starter project](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter) that may be of some help. It uses react-app-rewired [configuration](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/create-react-app-starter/config-overrides.js) for handling ESM and libraries without polyfills.

**Comment by Beardev118** [comment]
This is related with CRA5.0 and craco 5.0.0.
I have solved this issue by updating the craco version.
