### ISSUE TITLE
When calling spl-token --version

### ISSUE THREAD

**Issue by Elko-Lemiso** [solana-labs/solana-program-library#3196]
Im having an issue on my aws instance, 
After running spl-token with any arg, I get the following error

`spl-token: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

I thought that maybe it has somethin to do with my shared libraries, 

so after running
`ldconfig -p | grep libssl`

This is what I get 

```
        libssl3.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl3.so
        libssl.so.3 (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so.3
        libssl.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libssl.so
```

What I notice is that there is no `libssl.so.1.1` listed, does that account for the error?

So next I searched for how to add libssl.so.1.1 to the shared libs, 
I found an article saying you have to edit /etc/ld.so.conf.d/.conf and add the path to the lib. 
So I created the file and added the path /snap/core18/2344/usr/lib/x86_64-linux-gnu/libssl.so.1.1.

No success

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, and invite you to create an issue on StackOverflow with the "solana" tag, or join us on Discord in the #developer-support channel https://discord.gg/solana.

To quickly answer this, that's exactly the source of the error.  People have not had easy success with the library available from snap since you need to tell your system to look there.  You can install this instead with:

```
apt install libssl1.1
```

**Comment by Elko-Lemiso** [comment]
FIxed this by running everything locally
