### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by harsh4786** [solana-labs/solana-program-library#3198]
Do we need an anchor wrapper around the confidential_transfers program? Most of the instructions are marked with `#[cfg(not(target_os = "solana"))]` so i'm guessing that might be the reason my anchor code isn't building, i have almost finished with the wrapper but need some help with errors.

**Comment by joncinque** [comment]
We don't use GitHub for support, and invite you to join us in #developer-support on Discord: https://discord.gg/solana.  Very quickly though, not all of the instructions are meant to be used on-chain in a CPI context, which is why some of them are marked with `#[cfg(not(target_os = "solana"))]`.  That means that there should only be an anchor integration for these on TS, and not for CPIs.
