### ISSUE TITLE
Feature Request - spl-token - Add option to transfer and close account in same transaction

### ISSUE THREAD

**Issue by grimAgent** [solana-labs/solana-program-library#3262]
Basically what the title says

Right now, if I'm transfering an NFT to someone else, I need to make use 2 methods and hence 2 transactions. 
First `transfer` and then  `closeAccount`

Was wondering it it's possible to allow the `transfer` method to have an optional method to do the closing of the account within the same transactions

Thanks

**Comment by joncinque** [comment]
We may be confusing the terminology of "transaction" and "instruction", but it's currently possible to do what you're asking.  You can create a transaction and add two instructions -- one to transfer, and another to close, ie:

```
const transaction = new Transaction().add(transferInstruction, closeInstruction);
```

Since it's possible to do what you're saying by putting `transfer` and `close` in the same transaction, we will not create a separate instruction which does both.  This is not a feature that we will support, neither on the program nor the client.
