### ISSUE TITLE
Add a fallback implementation of getrandom for unsupported targets

### ISSUE THREAD

**Issue by the-mercenaries-ltd** [solana-labs/solana-program-library#3276]
I'm trying to compile all the programs using `cargo-build-bpf`.

I think it won't compile because this repo depends on solana modules, which in turn, don't support getrandom.

This is discussed in the docs here: https://docs.solana.com/developing/on-chain-programs/developing-rust#depending-on-rand

The solution is usually to add to the Cargo.toml
`getrandom = { version = "0.1.14", features = ["dummy"] }` or `getrandom = { version = "0.2.2", features = ["custom"] }`

However no package in this module depends directly on getrandom so it's unclear at a glance which Cargo.toml need to have the workaround added, and which version of getrandom to use.

More investigation needed.

**Comment by joncinque** [comment]
In your project, after the initial build, there should be a Cargo.lock file which defines all of the crates included in your build.  From there, you can see which version of `getrandom` is being used, along with the chain of dependencies, so you can either remove dependencies that transitively depend on `getrandom` or add either version as needed.

Adding a fallback implementation of getrandom on the BPF side could be dangerous, since it could lead people to wrongly assume that they have randomness. By specifying the dependency in your program explicitly, it's totally clear.

Either way, if you have more questions about this, it's best to ask in the Solana Stack Exchange https://solana.stackexchange.com/
