### ISSUE TITLE
token: Consider adding ability to close a mint through the mint authority

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3435]
#### Problem

NFT compression is now live, but only tokens created with token-2022 are compressible.  There are millions of mint and token accounts that could be removed from the system if compressed, reducing the storage burden on nodes.  Additionally, NFT upgrades from token to token-2022 will not easily propagate through the system, since the upgraded NFT will have new mint and metadata addresses. 

#### Solution

Add the ability to close mints in token (and token-2022) if the current mint authority signs.

The most compelling argument in favor of this addition is compressing the millions of existing NFT mints and accounts.  It also creates a smoother upgrade path for NFTs, where they can keep the same mint and metadata addresses, and simply recreate the token under token-2022, which would greatly help adoption of token-2022.

The most compelling argument against this addition is changing the behavior of token at all, which is always a risky endeavor.  We've also said that we'd only change token for security fixes.

Does this make sense given the current design? Maybe. Since a token account can be closed by either the close authority or the owner, perhaps a mint should also be closable by either the close authority (only in token-2022) or the mint authority.  If a mint has 0 tokens, the mint authority decides if more can ever be created, so perhaps it should also decide to close the account entirely.

What possible issues could this create? The biggest one is unexpected re-use of mint addresses.  If an indexer previously thought of an address as a mint, and it becomes anything else, what happens? Someone could put out a spoof token program and recreate their mint at that address.  Owner checks would solve that, but there may be a frontend somewhere that doesn't check it.

It wouldn't be decentralization for one person to decide this, so I want to put this in the open.  Feel free to tag anyone else who might want to comment.

cc @aeyakovenko @austbot @mvines @CriesofCarrots @samkim-crypto @2501babe @t-nelson

**Comment by mvines** [comment]
👎🏼 for me for this idea in Tokenkeg. 
1. It adds a new non-essential feature into Tokenkeg. Risk!
2. Could be breaky in unknown ways. Mint accounts are expected to always be there right now, who knows what downstream affects this could have on apps if some are removed.
3. Unclear what authority should be able to close the mint. Mint authority perhaps but what about mints that released their mint authority: those are probably unclosable so now we have exception cases (which ties back to 1 and 2)
4. The "millions of inactive accounts" problem really ought to be solved at the validator level. Accounts that have not been touched for epochs can be moved to secondary account storage. Multiple ways to do this and approaching it at the validator level benefits non-token accounts as well.

Considering this for Token22 seems totally find to me though, or perhaps we don't bother and simply use the new NFT compression thing entirely

**Comment by aeyakovenko** [comment]
> It adds a new non-essential feature into Tokenkeg. Risk!
> Could be breaky in unknown ways. Mint accounts are expected to always be there right now, who knows what downstream affects this could have on apps if some are removed.

yea, this is the big question, which makes me want to lean no as well.

> Unclear what authority should be able to close the mint. Mint authority perhaps but what about mints that released their mint authority: those are probably unclosable so now we have exception cases (which ties back to 1 and 2)

That's not really an exception, its just that the mint authority has been released, so it can never be cleaned up.

> The "millions of inactive accounts" problem really ought to be solved at the validator level. Accounts that have not been touched for epochs can be moved to secondary account storage. Multiple ways to do this and approaching it at the validator level benefits non-token accounts as well.

Yea agreed. it would be really hard for any solution there to save on rent for users, but we can probably figure out a way to save space used on validators.

**Comment by 2501babe** [comment]
thinking about this a bit more, adding this to token would break other security guarentees. since the storage is merely deallocated and the regular create mint flow is used to initialize a "new" mint at the same address, then the issuer can do things like add a freeze authority or change the decimals value. the latter could be a cause for concern if third party programs hardcode decimals for specific mints or implicitly depend on them. eg say, a vault that creates its own voucher mint with the same decimals as the parent

(now that i think about it this might be an interesting attack vector even for fresh mints, on loan programs that allow permissionless vault creation)

also im looking at the current impl of `process_close_account` in 22 now and this isnt necessarily a path to mass migration. control of the account is reassigned to system, so it would depend on the minter retaining the privkey to the original account, which many may not because it serves no purpose after the account is created. also it isnt clear to me how an nft issuer would get all of their users to burn their tokens so that the mint could be closed at all. obviously these requirements could be relaxed, but relaxing them starts to make my brain itch

aside from the risks tho i think leaving token as-is might be better for migration because it means theres two stories (dont migrate, migrate at new address) instead of like four, that nft platforms and stuff will need to handle

**Comment by aeyakovenko** [comment]
> also im looking at the current impl of process_close_account in 22 now and this isnt necessarily a path to mass migration. control of the account is reassigned to system, so it would depend on the minter retaining the privkey to the original account, which many may not because it serves no purpose after the account is created. also it isnt clear to me how an nft issuer would get all of their users to burn their tokens so that the mint could be closed at all. obviously these requirements could be relaxed, but relaxing them starts to make my brain itch

Generally a PDA would control the account and the mint address, and for compressed NFTs, the account addresses as well.  That program can allocate and deallocate the mint + accounts at will.

**Comment by aeyakovenko** [comment]
@mvines @joncinque 

I think allowing account cleanup is gonna be a bit dangerous for Token22 as well.  We should restrict close to Accounts that are derived from deterministic addresses from the mint.

`PDA(<Deterministic Mint Account Program>>, Mint authority)`

Only Mint's created from that program can be closed.

**Comment by t-nelson** [comment]
agreed with all of the above regarding opposition due to risk.  the only time i see it being completely safe to close a mint is if it has zero supply which, as stated above, seems like a rare and difficult to achieve case
