### ISSUE TITLE
token-cli: Can't mint using `--owner` flag

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#3684]
#### Problem

As reported in https://solana.stackexchange.com/questions/3569/spl-token-cli-unexpected-behaviour, we cannot mint to a destination using the `--owner` flag if it's just a pubkey.  So for example, this flow fails:

```
solana-keygen new -o mint.json
solana-keygen new -o authority.json
solana-keygen new -o owner.json
> D2eiS1H3tZKeMPZY1fgZF2NpctUYrrG8MEnaEvqq3gXA, for example

spl-token create-token mint.json -
spl-token create-account mint.json --owner D2eiS1H3tZKeMPZY1fgZF2NpctUYrrG8MEnaEvqq3gXA

spl-token mint mint.json 10 --owner D2eiS1H3tZKeMPZY1fgZF2NpctUYrrG8MEnaEvqq3gXA
> Errors with "error: missing signature for supplied pubkey: D2eiS1H3tZKeMPZY1fgZF2NpctUYrrG8MEnaEvqq3gXA"
spl-token mint mint.json 10 --owner D2eiS1H3tZKeMPZY1fgZF2NpctUYrrG8MEnaEvqq3gXA --mint-authority authority.json
> Errors with "error: The argument '--mint-authority <KEYPAIR>' was provided more than once, but cannot be used multiple times"
```

But the help message for mint says:

```
spl-token mint -h
Mint new tokens

USAGE:
    spl-token mint [FLAGS] [OPTIONS] <TOKEN_ADDRESS> <TOKEN_AMOUNT> [--] [RECIPIENT_TOKEN_ACCOUNT_ADDRESS]

.........

ARGS:
    <TOKEN_ADDRESS>                      The token to mint
    <TOKEN_AMOUNT>                       Amount to mint, in tokens
    <RECIPIENT_TOKEN_ACCOUNT_ADDRESS>    The token account address of recipient [default: associated token account for --owner]
```

#### Solution

There's a few possible approaches. To start, we shouldn't alias `owner` for `mint-authority` during `mint`, since we do typically use the ATA of `--owner`.  We can have the `--owner` flag be its own thing, that conflicts with `RECIPIENT_TOKEN_ACCOUNT_ADDRESS`, defaults to the default signer, and derives the ATA if the recipient token account address is not provided.

cc @2501babe for some more thoughts

**Comment by 2501babe** [comment]
imo we shouldnt overload the meaning of `--owner` like this, since its generally used to switch the authority from the point of view of what is being authenticated. eg, in `authorize` it controls the mint/account authority for the mint/account being modified, in `transfer` it controls the signer of the sender token acocunt, etc. in `mint` the mint is the entity taking authenticated action, so i think `--owner` is properly a synonym for `--mint-authority` here

also `--owner` controls the value of `default_signer`

id make a new flag like `--recipient-wallet` or `--recipient-owner` or something, that conflicts with `RECIPIENT_TOKEN_ACCOUNT_ADDRESS`, and fall back to `--owner` if both are missing, for backwards compat reasons

`--owner` is meant to be equivalent to `default_signer`, altho this gets kind of ugly because the cli validate the parameter to be a pubkey or signer, but config only uses it if its a signer. you can see config treat this mapping as if it ought to be bidirectional:
```
        let default_signer: Arc<dyn Signer> = {
            if let Some(owner_path) = matches.value_of("owner") {
                signer_from_path_with_config(matches, owner_path, "owner", wallet_manager, &config)
            } 
            ...
        }
```

```
    pub(crate) fn associated_token_address_for_token_and_program(
        &self,
        token: &Pubkey,
        program_id: &Pubkey,
    ) -> Pubkey {
        let owner = self.default_signer.pubkey();
        get_associated_token_address_with_program_id(&owner, token, program_id)
    }
```

`--owner` is generally used to switch the authority from the point of view of what is being authenticated. eg, in `authorize` it controls the mint/account authority for the mint/account being modified, in `transfer` it controls the signer of the sender token acocunt, etc. in `mint` the mint is the entity taking authenticated action, so i think `--owner` is properly a synonym for `--mint-authority` here
