### ISSUE TITLE
compat issues for cli release 2.1.0

### ISSUE THREAD

**Issue by 2501babe** [solana-labs/solana-program-library#3687]
ok so i created a 2.1.0 tag, and prior to pushing it to cargo, did a test run with `scripts/cargo-install-all.sh` from the monorepo on 1.10. this is the script that is used to build the binary tarball hosted on the site. unfortunately i got this:
```
+ /home/hana/work/solana/solana/cargo install --locked spl-token-cli --root /tmp/lol --path /home/hana/work/solana/solana-program-library/token/cli
+ exec cargo +1.59.0 install --locked spl-token-cli --root /tmp/lol --path /home/hana/work/solana/solana-program-library/token/cli
error: failed to load manifest for workspace member `/home/hana/work/solana/solana-program-library/token-upgrade/cli`

Caused by:
  failed to load manifest for dependency `spl-token-client`

Caused by:
  failed to parse manifest at `/home/hana/work/solana/solana-program-library/token/client/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
```

caused by the addition of this:
```
[features]
default = ["display"]
display = ["dep:solana-cli-output"]
```

because this feature is nightly in 1.59

i guess the question is, do we want to mess around with the monorepo build stuff to enforce our desired rust version? since i know we have the `rust-toolchain.toml` file, which i didnt know was being ignored. or can we un feature-lock the dependency, or accomplish the intent here through some other syntax, or something?

cc @joncinque

**Comment by karteljnr** [comment]
Package management is awful, you should quit right now
Package management is a nasty domain. Really nasty. On the surface, it seems like a purely technical problem, amenable to purely technical solutions. And so, quite reasonably, people approach it that way. Over time, these folks move inexorably towards the conclusion that:
software is terrible
people are terrible
there are too many different scenarios

4.nothing will really work for sure
it’s provable that nothing will really work for sure
our lives are meaningless perturbations in a swirling vortex of chaos and entropy
If you’ve ever created…well, basically any software, then this epiphanic progression probably feels familiar. It’s the design death spiral — one that, experience tells us, is a signal to go back and reevaluate expectations and assumptions. Often enough, it turns out that you just hadn’t framed the problem properly in the first place. And — happy day! — that’s the case here: those who see package management as a purely technical problem are inevitably, even if subconsciously, looking for something that can completely and correctly automate upgrades.
Stop that. Please. You will have a bad time.

**Comment by karteljnr** [comment]
Package management is at least as much about people, what they know, what they do, and what they can reasonably be responsible for as it is about source code and other things a computer can figure out. Both sides are necessary, but independently insufficient.
Oh but wait! I’m already ahead of myself.

**Comment by 2501babe** [comment]
haha jk i closed this like "well we are gonna build against 1.13/1.14 now so this doesnt matter" exactly 30 seconds before my 1.13 build failed because theyre still on 1.59 there too

**Comment by 2501babe** [comment]
wait fuck and then 30 seconds after that i hit the librocksdb thing again. the issue has nothing to do with the _solana_ version, its because we are on different _rust_ versions

**Comment by 2501babe** [comment]
ok after a brief existential crisis ("the 1.60 change was... me? i... did that? why did i do that? did i break it???") i have been enlightened and understand all things

1.13.x is on 1.59 because it is 1.10.x with glasses and mustache. the reason i moved us to 1.60 in the 1.11.x upgrade is because 1.11.x did in fact go to 1.60. no error has been committed

we need to lock 1.10.x _and 1.13.x_ to 2.0.17, and the forthcoming 2.1.1 can live in the elysian land of 1.14.x alone
