### ISSUE TITLE
"spl-token accounts" command returned http error 429

### ISSUE THREAD

**Issue by injaan** [solana-labs/solana-program-library#3730]
"spl-token accounts" command  returned "HTTP status client error (429 Too Many Requests) for url (https://api.mainnet-beta.solana.com/)" message after few seconds later if I use solana-mainnet RPC endpoint it is OK whe I use other rpc endpoints or devnet endpoint. Also this error is returned from getTokenAccountsByOwner method of web3js

**Comment by joncinque** [comment]
This would be an issue on the side of the RPC providers and not SPL. The RPC providers may have strict rate-limits on this call or simply not allow it at all.  You can bring it up with the node provider directly.  In the case of `api.*.solana.com` endpoints, they're provided by TritonOne https://www.triton.one/#/

Closing this since it's out of scope, the CLI is doing the right thing.
