### ISSUE TITLE
API request

### ISSUE THREAD

**Issue by indynov** [solana-labs/solana-program-library#3797]
Could you add a splToken.getOwnersByMints() feature where you can pass an array of 1000 mint addresses and it will give an array of 1000 owners? This would make it much easier to get the data for building something like this https://howrare.is/mystopians/owners otherwise you need to use findAllByCreators to get all mint address, then 1 by 1 use connection.getTokenLargestAccounts() then splToken.getAccount() which can lead to 10,000 RPC requests to get the results. With this feature you could get the same results in 10 RPC requests which would speed it up a lot.

**Comment by joncinque** [comment]
While this definitely sounds like an important use-case for NFTs, it will be better to implement this functionality as a Geyser plugin rather than as a new RPC call.

The best intermediate option is to have a new call like `getTokenLargestAccount` which accepts multiple mint addresses, but since the future is to implement these kinds of calls through Geyser, it won't make sense to support this at the RPC level unfortunately.

You can learn more about Geyser at https://docs.solana.com/developing/plugins/geyser-plugins
