### ISSUE TITLE
Allow for multiple delegates per Token Account

### ISSUE THREAD

**Issue by jamesrp13** [solana-labs/solana-program-library#3858]
**Problem:** At present, there can only be one delegate per Token Account. This means that any delegation to a program that will perform ongoing or future actions on behalf of a user will likely be interrupted by users interacting with a separate program that also requires delegation. 

**Solution:** My preferred solution would be to add this to the Token Program itself, but that seems unlikely for the program that is live given that it would require changes to account structures. The next best solution is probably a separate program (like the ATA program) that becomes the new standard through which delegation is performed. This program would handle delegate approvals and would itself be the single delegate for all token accounts moving forward. It would then be responsible for routing delegation functions properly.

**Use cases:** While we certainly should be smart about how we use delegation, there are plenty of cases where delegation is what provides for the best end user experience. The primary example I can think of is for subscription payments. Without delegation, this can only happen via some sort of escrow pattern or making users manually transfer funds at each subscription interval. That would suck.

Idk what else we should put in here, but let's at least get the conversation started.

**Comment by jamesrp13** [comment]
It appears @mfrager has made something along these lines already: https://github.com/atellix/token-delegate

Curious what others think of it

**Comment by mfrager** [comment]
If people want to use this program as well, I will make it immutable for security purposes. Any feedback is very welcome! Thanks.

**Comment by jamesrp13** [comment]
Thanks @mfrager! It may be a good interim step to having a more formal multi-delegate pattern integrated into the token program or at a minimum made part of the SPL

**Comment by dankelleher** [comment]
Isn't delegating to a PDA owned by a 1-of-n multisig program a more composable solution? This program would not need to be specific to SPL-Token, but would handle any comparable use case.

I'm thinking along the lines of the [cryptid](https://github.com/identity-com/cryptid) model:

1. define a set of linked addresses (your multi-delegates)
2. set the token account delegate to an account abstraction PDA based on that set
3. transactions from one of the delegates would go through the account abstraction program to check the delegate is in the list

Upsides:

- More composable - the delegation logic would be encapsulated in the account abstraction
- More powerful - you could add rules governing delegates to the account abstraction program (e.g. delegate A may spend up to X tokens)
- More flexible - use the same account abstraction on other programs

Downsides:
- Tx compute/size overhead of piping through the account abstraction program
- More complexity on the client side

**Comment by mfrager** [comment]
I’m not sure the previous reply understands exactly the problem to be solved.

The problem is that multiple programs, written by entirely different people/teams want to set allowances on the same token account, but without overwriting and replacing the tokens delegated to the earlier programs.

That why there should be just 1 PDA that is re-used by everyone as the main delegate. A token is either linked to a 1-N sub-delegation process or it’s not.

Also, N should be able to grow as large as necessary. We don’t want to limit future delegates to an arbitrary number.

A multisig is not necessary (totally different problem) and not all of the downstream delegates would be known at first.

The idea is that a user would add a delegate for one project today and then later add a delegate for another project… without interrupting the first, and so on.

This allows multiple implementations of streaming payments, subscriptions, etc. without one implementation stepping on the toes of another, and interrupting the previous subscriptions, which results in a poor and confusing user experience.

Given these requirements, any design should be as simple, and completely foolproof as possible. This isn’t a place where any additional complexity nor feature-creep is welcome.

**Comment by nickgarfield** [comment]
I support this! To compete with fiat payment services, it's critical that the token program does not overly constrain the design space for developers. The current token program has a single-delegate approval model which forces merchants and programs to fight over the authority to spend from users' associated token accounts. In fiat payment systems, this problem is solved simply by allowing multiple parties to hold "direct debit" authority over the same account at the same time (ref: https://en.wikipedia.org/wiki/Direct_debit). To unlock better user experiences on Solana and encourage developers to build more secure payment products, it's important for the token program to provide a scalable "pull payment" interface that doesn't introduce unncessary artificial scarcities.

To implement this in token22 will require a few modifications to the current account schema, but there are solutions that minimize impact to existing interfaces. Below, I've outlined one that strikes me doable. I haven't dug too deep into the code, so there may be implementation complexities I'm not aware of. If you spot design issues, please call them out! If you have no objection to the interfaces but _do_ object to including them in token22, it would be great to get a breakdown of what the alternative scaling solutions are here.
 
### State

- [ ] Remove the `delegate` and `delegated_amount` properties from the `Account` struct. 
- [ ] Introduce an `Approval` account type for recording the amount that each delegate is authorized to withdraw from a given source account.
- [ ] The pdas of approval accounts should be derived from (1) the `source` token account address and (2) the `delegate` address. 

```rs
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq)]
type Approval {
  /// The spending amount.
  pub amount: u64,

  /// The spending authority.
  pub delegate: Pubkey,

  /// The account from which tokens can be spent.
  pub source: Pubkey 
}
```



### Instructions 

- [ ] To initialize, update, and close `Approval` accounts, the `Approve` and `Revoke` instructions need to make room for it in their account inputs.

```rs
    ///   0. `[]` The source account.
    ///   1. `[]` The delegate.
    ///   2. `[signer]` The source account owner.
    ///   3. `[writable]` The approval account.

    /// Approves a delegate.  A delegate is given the authority over tokens on
    /// behalf of the source account's owner.
    ///
    /// Accounts expected by this instruction:
    ///
    ///   * Single owner
    ///   0. `[]` The source account.
    ///   1. `[]` The delegate.
    ///   2. `[signer]` The source account owner.
    ///   3. `[writable]` The approval account.
    ///
    ///   * Multisignature owner
    ///   0. `[]` The source account.
    ///   1. `[]` The delegate.
    ///   2. `[]` The source account's multisignature owner.
    ///   3. `[writable]` The approval account.
    ///   4. ..3+M `[signer]` M signer accounts
    Approve {
        /// The amount of tokens the delegate is approved for.
        amount: u64,
    },

    /// Revokes the delegate's authority.
    ///
    /// Accounts expected by this instruction:
    ///
    ///   * Single owner
    ///   0. `[]` The source account.
    ///   1. `[signer]` The source account owner or current delegate.
    ///   3. `[writable]` The approval account.
    ///
    ///   * Multisignature owner
    ///   0. `[]` The source account.
    ///   1. `[]` The source account's multisignature owner or current delegate.
    ///   3. `[writable]` The approval account.
    ///   4. ..2+M `[signer]` M signer accounts
    Revoke,
```
 

- [ ] Finally, the `TransferChecked` and `TransferCheckedWithFee` instructions also need to make room for the approval account. If the user is transferring tokens from an account they own, the approval account may be uninitialized.

```rs
    /// Accounts expected by this instruction:
    ///
    ///   * Single owner/delegate
    ///   0. `[writable]` The source account.
    ///   1. `[]` The token mint.
    ///   2. `[writable]` The destination account.
    ///   3. `[signer]` The source account's owner/delegate.
    ///   4. `[writable]` approval account.
    ///
    ///   * Multisignature owner/delegate
    ///   0. `[writable]` The source account.
    ///   1. `[]` The token mint.
    ///   2. `[writable]` The destination account.
    ///   3. `[]` The source account's multisignature owner/delegate.
    ///   4. `[writable]` approval account.
    ///   5. ..4+M `[signer]` M signer accounts.
    TransferChecked {
        /// The amount of tokens to transfer.
        amount: u64,
        /// Expected number of base 10 digits to the right of the decimal place.
        decimals: u8,
    },
```

**Comment by dankelleher** [comment]
> That why there should be just 1 PDA that is re-used by everyone as the main delegate. A token is either linked to a 1-N sub-delegation process or it’s not.
>
> Also, N should be able to grow as large as necessary. We don’t want to limit future delegates to an arbitrary number.

I think we're saying the same thing. The token account still only contains one single delegate. This is a PDA owned by a separate program. There is an account, which contains the delegate keys, and the program checks whether the delegate signing the tx belongs to that account, and if so, executes the call on the token program, signing via the single delegate PDA that it controls. 

> A multisig is not necessary (totally different problem) and not all of the downstream delegates would be known at first.

I was using "multisig" as a shorthand to describe any 1-of-n structure, such as the one above. I didn't mean to imply that the N is fixed or known up-front.  If any number of keys have permission on a token account, then that is essentially a 1-of-n multisig.

> Given these requirements, any design should be as simple, and completely foolproof as possible. This isn’t a place where any additional complexity nor feature-creep is welcome.

This is a legitimate criticism of the account abstraction approach. But we have to weigh up the complexity of having mutliple composable programs on one side with bloating individual programs (such as the token program) on the other. The token program should have one delegate, which can either be an EOA or a PDA, and it should be completely agnostic to the logic behind that.

**Comment by nickgarfield** [comment]
> But we have to weigh up the complexity of having mutliple composable programs on one side with bloating individual programs (such as the token program) on the other. The token program should have one delegate, which can either be an EOA or a PDA, and it should be completely agnostic to the logic behind that.

If we're going to try to solve the token program's scaling problems by delegating to a 1-of-N or a multisig, then the entire ecosystem needs to socially agree on which program we are all going to use by convention. If there is any disagreement between teams and some programs use one solution while other programs use another, then the competition over the user's ata account will never be resolved. 

"Pull payments" are so vital in to the payments industry that I do not see OP's proposal as bloat or feature-creep. Quite the contrary. The token program today has an unintended design _flaw_ that prevents developers from being able to build the kinds of products that users actually want. We should not band-aid this problem with "L2 programs" and start an unnecessary standards war when we could easily solve it at the root level in the token program.

**Comment by mfrager** [comment]
I think everyone on this thread is more or less converging on the same idea.

I've already built an implementation for this, which I've been using on mainnet for several months (program ID: TKDLLzzmBD7Rwbz6PS4XDFDr5w4ApSBRNC4wninsX7M). If people wouldn't mind taking a look at this existing code, and see if it's already viable for this purpose, or if there needs to be further changes, or even a new program:

https://github.com/atellix/token-delegate/blob/master/programs/token-delegate/src/lib.rs

Comments welcome.
