### ISSUE TITLE
TokenAccountNotFoundError when using getAssociatedTokenAddress() on specific NFTs

### ISSUE THREAD

**Issue by incogiscool** [solana-labs/solana-program-library#3916]
Hey, when I use the `getAssociatedTokenAddress()` function, it works great for most NFTs, except NFTs such as the MKRS (which is staked/locked) collection. When I try and use the function on those NFTs, I get a `TokenAccountNotFoundError`.
![image](https://user-images.githubusercontent.com/94598096/207852037-5fcca860-96ae-436b-93b7-3598c6b1c4ce.png)

This is the code: 
```
    const nftTokenAcc = await getAssociatedTokenAddress(
      nftMint,
      //@ts-ignore
      this.publicKey
    );
```

The NFT in question's solscan: [https://solscan.io/address/8r7qv9byLTbcAD1P616KeEG5KqJD7LVnNuDCVXjUqVwG
](https://solscan.io/address/8r7qv9byLTbcAD1P616KeEG5KqJD7LVnNuDCVXjUqVwG
)

**Comment by jordansexton** [comment]
Can you provide the public keys you are calling that function with?

**Comment by jordansexton** [comment]
TokenAccountNotFound here just means that there wasn't a Token account found at the ATA of the mint and owner address provided. The mint address you provided looks fine, and the token account that holds that NFT is https://explorer.solana.com/address/HJ7kqyvgHfujfNAryE1pXR9bzpGG9dgJtEDKJssffq7x

**Comment by incogiscool** [comment]
> TokenAccountNotFound here just means that there wasn't a Token account found at the ATA of the mint and owner address provided. The mint address you provided looks fine, and the token account that holds that NFT is https://explorer.solana.com/address/HJ7kqyvgHfujfNAryE1pXR9bzpGG9dgJtEDKJssffq7x

Is there a way to bypass this error or is there a different function that can fetch the token account even in this instance?

FYI: Just responding to your first comment, the `nftMint` is the mint address of the nft and the `this.publicKey` is the public key of the owner.

Here is an extended screenshot:
![image](https://user-images.githubusercontent.com/94598096/208240430-aded38b5-a51c-44a7-bf5b-0363b6aa8bb1.png)

**Comment by ceciEstErmat** [comment]
Had the same error please make sure you are on the latest lib version. If the error is happening on a local validator during testing make sure to update to the latest version there also

**Comment by incogiscool** [comment]
> Had the same error please make sure you are on the latest lib version. If the error is happening on a local validator during testing make sure to update to the latest version there also

The error is occurring on the Mainnet (I'm using quicknode). I just upgraded all the packages on the lock file and the same error occurred.

**Comment by jordansexton** [comment]
Here's the token account in question (`HJ7k`): https://explorer.solana.com/address/HJ7kqyvgHfujfNAryE1pXR9bzpGG9dgJtEDKJssffq7x

Here's the transaction that created it: https://explorer.solana.com/tx/5mmxiqDt5mj3HfWLmKALdR2kVjY9kacjH2z2gfwwQNLVKnSvBstMEmxpL8D7qZYAuCsU8TQkWNvi2XowtZDGsHXw

Looking at the 3rd account input, we see:

<img width="1132" alt="Screen Shot 2022-12-19 at 12 24 16 PM" src="https://user-images.githubusercontent.com/1173161/208494104-c1acc03c-45ab-4df4-8909-5f5e12fc93aa.png">

Here we see the token account `HJ7k`, as a signer of the instruction. By definition, this means that it is not an ATA, because an ATA must be a PDA and therefore cannot be a signer here.

Looking at some instructions in this transaction:

<img width="1046" alt="Screen Shot 2022-12-19 at 12 26 51 PM" src="https://user-images.githubusercontent.com/1173161/208494570-af004bb0-2778-4cfe-81ad-bb638507e9f2.png">

We can see that the token account was created directly, by creating a system account and initializing it, rather than using the ATA program to create and initialize it. This is what's referred to as an _auxiliary_ token account. It is not an ATA, and cannot be found using the the `getAssociatedTokenAddress` function, because its address is a public key, not a PDA.
