### ISSUE TITLE
failed to select a version for `spl-associated-token-account` which satisfies dependency `solana-transaction-status = "^1.15.2"`

### ISSUE THREAD

**Issue by gitmalong** [solana-labs/solana-program-library#4141]
Hi!

In my app I want to use the latest version of the `solana-client = "1.15.2"`  with `spl-associated-token-account = "1.1.3"` which is currently not possible due to a dependency version selection issue:

```rust
error: failed to select a version for `spl-associated-token-account`.
    ... required by package `solana-transaction-status v1.15.2`
    ... which satisfies dependency `solana-transaction-status = "^1.15.2"` of package `myapp  v0.1.0 (/Users/user/myapp)`
versions that meet the requirements `=1.1.2` are: 1.1.2

all possible versions conflict with previously selected packages.

  previously selected package `spl-associated-token-account v1.1.3`
    ... which satisfies dependency `spl-associated-token-account = "^1.1.3"` of package `myapp v0.1.0 (/Users/user/myapp)`

failed to select a version for `spl-associated-token-account` which could resolve this conflict
Error: recursive dependency update failed
```

**Comment by joncinque** [comment]
This is expected behavior, you'll need to use spl-associated-token-account version 1.1.2 with solana-transaction-status because it pins to spl version 1.1.2: https://crates.io/crates/solana-transaction-status/1.15.2/dependencies

Separately, you should use solana-client version 1.14.17, since the 1.15 line has been abandoned.

We don't use GitHub for developer support, so in the future please ask your question on a dedicated forum like https://solana.stackexchange.com/
