### ISSUE TITLE
token-2022: Consider prohibiting creating non-transferable accounts *without* immutable ownership

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana-program-library#5884]
#### Problem

It's possible to create a token account on a mint with the non-transferable extension *without* immutable ownership enabled. Immutable ownership is enforced during *minting*, so it's impossible to mint a non-transferable token to an account without immutable ownership.

This can be confusing, because it seems like it might be possible to have non-transferable tokens in an account with transferable ownership.

#### Solution

Consider throwing an error when trying to initialize a token account on a non-transferable mint *without* immutable ownership.

**Comment by buffalojoec** [comment]
So, if I'm understanding this correctly:
- In order to mint tokens to a non-transferable account, that destination must have an immutable owner
- In order to transfer tokens from a non-transferable account, you can't

What would be the reason to allow creating a non-immutable owner token account on a non-transferable mint? I would say this only makes sense if the non-transferable extension can be removed, which at the moment it does not appear is the case.

**Comment by joncinque** [comment]
> What would be the reason to allow creating a non-immutable owner token account on a non-transferable mint?

I can't remember why we did it that way. It looks like it was just done like that in https://github.com/solana-labs/solana-program-library/pull/2912 without any other questions.

> In order to transfer tokens from a non-transferable account, you can't

Also, lol

**Comment by quminghaonanya** [comment]
Can I try this issue? I'm going to

**Comment by quminghaonanya** [comment]
Can I have a try on this issue,
I will return the NonTransferableNeedsImmutableOwnership error when trying to initialize an account on a non-transferable mint without immutable ownership.

**Comment by joncinque** [comment]
Yep that's the idea, and no need to ask for permission, go for it! We'll review your PR when it comes in

**Comment by joncinque** [comment]
Fixed in #6206
