### ISSUE TITLE
[HELP] I sent my Solana token to my ATA address in my new wallet. How do I recover?

### ISSUE THREAD

**Issue by hashfi-motion** [solana-labs/solana-program-library#6022]
As the title said. Instead sending to my new wallet Solana address, I sent my Solana token to my new wallet ATA address, the explorer said success but the balance still says 0.
How do I recover from this? Is it possible or not?

I use Trust Wallet as my sender, and my receiver use Solflare.
I tried exploring with `solana-cli`, but seems can't find the answer I was looking for. 
I already have my Solflare wallet in my `solana-cli`.

If this is not the right place to ask this question please let me know where should I ask my problem.

**Comment by CriesofCarrots** [comment]
Hi, we don't provide wallet support. Your best bet may be to seek Solflare support.
If the issue is a "nested" ATA and you want to resolve yourself, see this ATA instruction: https://github.com/solana-labs/solana-program-library/blob/d313ec13d63b4a5677079c672156bc6e77751ede/associated-token-account/program/src/instruction.rs#L56
But there isn't `spl-token-cli` support for it.
Further questions should go to: https://solana.stackexchange.com/questions/ask

**Comment by hashfi-motion** [comment]
Thanks for the response, I honestly don't get it how do I use `RecoverNested`

So I just look up and found my answer here:
https://solana.stackexchange.com/questions/5448/how-can-i-use-instructionrecover-nested

I also don't know if the site is 100% legit, so I probably advise to move your money to new wallet if possible. If you think it's shady and might drain wallet please let me know!
