### ISSUE TITLE
Error: failed to compile `spl-token-cli v3.3.0`, with latest Rust and Solana cli along with cargo cant install spl token cli

### ISSUE THREAD

**Issue by Dante9988** [solana-labs/solana-program-library#6027]
When installing using command `cargo install spl-token-cli` I get the following error

error: failed to compile `spl-token-cli v3.3.0`, intermediate artifacts can be found at `/tmp/cargo-install8eI2bJ`

**Comment by buffalojoec** [comment]
Hey there, I can't seem to reproduce the issue. I think it would help if you shared the specific version of `cargo` you're using. The Solana CLI shouldn't be involved here.

There's also a `--verbose` flag you should use when running `cargo install` in order to potentially show some more information about the error.
