### ISSUE TITLE
token-2022: Token Metadata instructions do not automatically transfer SOL for rent

### ISSUE THREAD

**Issue by ZYJLiu** [solana-labs/solana-program-library#6654]
Currently, the token-2022 [metadata extension instructions](https://github.com/solana-labs/solana-program-library/blob/master/token/program-2022/src/extension/token_metadata/processor.rs) only allocate the extra spaced required for the metatdata, but do not automatically calculated the rent lamports required for the extra space. In the test files for the extension, it looks like the calculation is done on the client using various helper functions and a SOL transfer instruction is added if needed.

Would it be possible to having the calculations and SOL transfer instruction (via cpi) included in the instruction handlers instead? Or is there a reason this functionality isn't included in the instructions?

This would simplify invoking the instructions for the end user. For example, if a user wants to add more metadata to the mint account, its implied they would like to transfer the SOL required for the extra data to the account.

**Comment by joncinque** [comment]
The lack of a `payer` is by design. If the token-metadata program does the SOL transfer, then the interface will require an account to be passed as a signer and mutable, along with the system program. This is extremely dangerous, since any program that accepts a wallet account as a signer and mutable, along with the system program, can immediately drain everything from that wallet.

Since we want other programs to implement the token-metadata interface, we need it to be safe for anyone to use to avoid easy rug pulls. It's much safer for client libraries to include required transfer instructions at the top-level of the transaction.
