### ISSUE TITLE
can't use library with web3.js 2.0+

### ISSUE THREAD

**Issue by ilanoh** [solana-labs/solana-program-library#7610]
how do you upgrade to web3 2.0 and keep using spl-token in the project?

**Comment by joncinque** [comment]
There are new auto-generated libraries being developed for web3.js v2 -- you can check out the one for token-2022 at https://github.com/solana-program/token-2022/tree/main/clients/js and token at https://github.com/solana-program/token/tree/main/clients/js.

Since development will soon be ending in this repo, closing the issue
